<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $enableAjax = themeOptions('enable_ajax'); ?>
<?php $_layout = themeOptions('layout'); ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<a class="back-to" href="javascript: history.go(-1)"><?php echo $this->__('Return to Previous Page') ?></a>
        
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view layout_<?php echo $_layout ?>">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div id="addedoverlay" style='display:none'> </div>
        <div id='added' style='display:none'></div>
        <div id='productname' style='display:none'><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></div>
<div class="product-shop">
            <div class="white-back">
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>
                    <?php echo $this->getPriceHtml($_product) ?>
                <div class="clear"></div>
                <?php echo $this->getTierPriceHtml() ?>
                 <div id="sn_icons">
        <!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a> 
<a class="addthis_button_tweet" tw:via="addthis"></a> 
<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>  
<a class="addthis_button_pinterest_pinit" pi:pinit:url="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>" pi:pinit:media="<?php echo $_product->getImageUrl(); ?>" pi:pinit:layout="horizontal">        </a> 

</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4ff558e34695d1c0"></script>
<!-- AddThis Button END -->
</div>
                <div id="full-description" class="box-description">
                    <h3>Product Details</h3>
                      <span itemprop="description"><?php echo $_product->getDescription(); ?></span>
                      <br/>
                      <span class="sku">Product Code: <?php echo $_product->getSku(); ?></span>
                </div>
	   <div id="size-guide">
<script type="text/javascript">
function newPopup(url) {
	popupWindow = window.open(
		url,'popUpWindow','height=700,width=698,left=10,top=10,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no,status=yes')}
</script>
<a href="JavaScript:newPopup('http://wwww.desireclothing.co.uk/media/wysiwyg/size-guide.jpg');">Size Guide<a/>
</div>
 <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <div id="container2"><?php echo $this->getChildChildHtml('container2', '', true, true) ?></div>     
        <?php endif;?>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <div id="container1"><?php echo $this->getChildChildHtml('container1', '', true, true) ?><div class="clear"></div></div>
                <?php endif;?>   
                
                <?php echo $this->getChildHtml('product_type_data_grouped') ?>
                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php endif; ?>  
                <?php if($_layout == 'horizontal'): ?>
                    <div class="clear"></div> 
                <?php endif; ?>  
                
                <?php echo $this->getChildHtml('other');?>
            </div>
            <?php if($_layout != 'horizontal'): ?>
                <div class="product_right">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('productview')->toHtml(); ?>
                </div>
            <?php endif; ?>
        </div>

 <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
        <div class="clearer"></div>
    </form>
    <script src="http://malsup.github.com/jquery.form.js"></script> 
    <script type="text/javascript">
    <?php if($enableAjax): ?>
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
		var url = jQuery('#product_addtocart_form').attr('action');
		url = url.replace("checkout/cart","ajax/index");    

        var msgHtml;
        var productImg = jQuery('.main-thumbnail').html();
        var windowOver = jQuery('#addedoverlay');
        var windowBox = jQuery('#added');
        var titleForBox = jQuery('#productname').text();   
        var data = {'isAjax':1}
        
        jQuery('#product_addtocart_form').ajaxForm({
            url: url,
            data: data,
            dataType: 'json',
            beforeSubmit: function(){    
                if(productAddToCartForm.validator.validate()){
                    windowOver.show();
                    windowBox.show().css({
                        backgroundImage: "url('<?php echo $this->getSkinUrl('images/loading.gif')?>')"
                    });                    
                }else{
                    return false;
                }
            },
            error: function(data){
	            windowBox.css({
       			      backgroundImage: 'none'
                }).html('<?php echo $this->__('Error') ?>');					   
                windowOver.one('click',function(){
		            hidewindow(windowBox,windowOver);                    
                });	       
                                 
                jQuery('#hidewindow').click(function(){
		            hidewindow(windowBox,windowOver);                    
                });
            },
            success : function(data,statusText,xhr ){
                if(data.status == 'SUCCESS'){
					_gaq.push(['_trackEvent','Button', 'Add to Cart', 'Product Detail Page', 1,'true']);
                    if(jQuery('.block-cart')){
                        jQuery('.block-cart').replaceWith(data.sidebar);
                    }
                    if(jQuery('.header .block-cart-header')){
                        jQuery('.header .block-cart-header').replaceWith(data.topcart);
                    }     
                    msgHtml = '<div class="added-content"><em>' + titleForBox + '</em> <?php echo $this->__(' added to your bag.') ?><div style="clear:both; height:20px;"></div><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View Bag & Checkout') ?></a></div>';             
                }else{
                    msgHtml = '<div class="added-content"><p class="error-msg" style="margin-bottom:15px;">' + data.message + '</p><a id="hidewindow" href="javascript:void(0);"><?php echo $this->__('Continue shopping') ?></a>&nbsp;<a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('View cart & checkout') ?></a></div>';
                }					   
               
                windowBox.css({
       			      backgroundImage: 'none'
                }).html(msgHtml);					   
                windowOver.one('click',function(){
    	            hidewindow(windowBox,windowOver);                    
                });	       
                                 
                jQuery('#hidewindow').click(function(){
    	            hidewindow(windowBox,windowOver);                    
                });	   
            }
        }); 
        
        function hidewindow(windowBox,windowOver){
            windowOver.fadeOut(400);
            windowBox.fadeOut(400).html('');	
        }

    //]]>
    <?php else: ?>
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    
    <?php endif; ?>
    </script>
    </div>
        <?php echo $this->getChildHtml('related_products') ?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('recently_viewed') ?>
</div>
