<?php if(count($this->getItemCollection()->getItems())): ?>    
<div class="block-related">
    <h5><?php echo $this->__('You may also be interested in the following product(s)') ?></h5>
    <br/><br/>
    <div class="clear"></div>
    <div id="mycarousel" class="related related-slider">
        <div class="slider" >        
        <?php $_i_related = -1; ?>
        <?php foreach($this->getItemCollection()->getItems() as $_item): $_i_related++; ?>
            <div class="slide <?php if((count($this->getItemCollection()->getItems()) == 4 && $_i_related == 3) || (count($this->getItemCollection()->getItems()) == ($_i_related + 1))) echo 'last' ?>">
                <div class="product">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(228) ?>" width="228" height="228" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
                        <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <!--a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a-->
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
        </div>
        <?php if(count($this->getItemCollection()->getItems()) > 4): ?>
            <div class="prev">&nbsp;</div>
            <div class="next">&nbsp;</div>         
        <?php endif; ?>      
        <script type="text/javascript">decorateList('mini-products-list', 'none-recursive')</script>
        <div class="clear"></div>
    </div>
    <?php if(count($this->getItemCollection()->getItems()) > 4): ?>
        <script type="text/javascript">
            jQuery('.related .prev').addClass('disabled');
            jQuery('.related').iosSlider({
                desktopClickDrag: true,
                snapToChildren: true,
                infiniteSlider: false,
                navNextSelector: '.related .next',
                navPrevSelector: '.related .prev',
                lastSlideOffset: 3,
                onFirstSlideComplete: function(){
                    jQuery('.related .prev').addClass('disabled');
                },
                onLastSlideComplete: function(){
                    jQuery('.related .next').addClass('disabled');
                },
                onSlideChange: function(){
                    jQuery('.related .prev').removeClass('disabled');
                    jQuery('.related .next').removeClass('disabled');
                }
            });               
        </script>           
    <?php endif; ?>    
</div>
<?php endif ?>
