<div id="top"></div>
<div class="header-container">
    <div class="header">
        <div class="header-left">
            <?php echo $this->getChildHtml('store_language') ?>         
            <?php if ($this->getIsHomePage()):?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>
        </div>
        <div class="header-center">
            <span class="welcome-msg"><?php echo $this->getWelcome() ?></span>
            <?php echo $this->getChildHtml('topBar') ?>   
        </div>        
        <div class="header-right">
        	<?php echo $this->getChildHtml('store_switcher') ?>
            <div class="minicart">
                <?php echo $this->getChildHtml('top_cart') ?>
            </div>  
            <?php echo $this->getChildHtml('currency') ?>  
            <div class="clear"></div>   
            <?php echo $this->getChildHtml('topLinks') ?>  
        </div>      
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <div id="submenu" class="topsubmenu">
     <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top_sub_menu')->toHtml() ?>
       <?php /*?> <div class="submenu-bite left">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('submenu_left')->toHtml() ?>
        </div>
         <div class="submenu-bite middle">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('submenu_middle')->toHtml() ?>
        </div>
        <div class="submenu-bite right">
         <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('submenu_right')->toHtml() ?>
        </div><?php */?>
        </div>
    <?php echo $this->getChildHtml('topBread') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>
</div>