<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
   

        <!--Start New Sort-->
              <div class="sort-by">
              <span class="sortby">SORT BY: </span>
              <span class="sortbylinks"><a href="<?php echo $categoryURL; ?>?dir=desc&order=created_at" title="New">Newest In</a></span>
              <span class="sortbylinks"><a href="<?php echo $categoryURL; ?>?dir=asc&order=price" title="Price from Low to High">Price (Low)</a></span>
              <span class="sortbylinks"><a href="<?php echo $categoryURL; ?>?dir=desc&order=price" title="Price from High to Low">Price (High)</a></span>
              </div> <!--End sort-by-->
 <!--End New Sort-->
         <div class="pager">
        <?php if( $this->isEnabledViewSwitcher() ): ?>
        <p class="view-mode">
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
            <label><?php echo $this->__('View as') ?>:</label>
            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if($this->isModeActive($_code)): ?>
                    <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>
                <?php else: ?>
                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php endif; ?>
        </p>
        <?php endif; ?>         
        
        <?php echo $this->getPagerHtml() ?>
        
        <div class="limiter">
            <label><?php echo $this->__('Show') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select> <?php echo $this->__('per page') ?>
        </div>
        
    </div>

</div>
<?php endif ?>
